project:
  type: website

website:
  title: "Shamindra Shrotriya"
  site-url: https://www.shamindras.com
  repo-url: https://github.com/shamindras/ss_personal_quarto_blog
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    creator: "@shamindraas"
    card-style: summary_large_image
  navbar:
    right:
      - text: research
        file: research.qmd
      - text: blog
        file: posts.qmd
      - text: "cv"
        href: data/pdfs/CV.pdf
      - text: "resume"
        href: data/pdfs/resume.pdf
      - icon: github
        href: https://github.com/shamindras
      - icon: twitter
        href: https://twitter.com/shamindraas
      - icon: rss
        href: posts.xml
  google-analytics: "UA-145015693-1"
  page-footer: 
    right:
      - text: blog source
        href: https://github.com/shamindras/ss_personal_quarto_blog

format:
  html:
    theme: ember.scss
    css: styles.css