project:
  type: website
  render:
    - "**/*.qmd"

website:
  title: "Shamindra Shrotriya"
  draft-mode: gone
  site-url: https://www.shamindras.com
  repo-url: https://github.com/shamindras/ss_personal_quarto_blog
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  reader-mode: true
  navbar:
    background: "#FFFFFF"
    foreground: "dark"
    right:
      - text: research
        file: research.qmd
      - text: blog
        file: posts.qmd
      - text: software
        file: software.qmd
      - text: "CV"
        href: data/pdfs/shamindra-shrotriya_CV.pdf
      - text: "teaching"
        href: data/pdfs/shamindra-shrotriya_teaching-statement.pdf
      - icon: github
        href: https://github.com/shamindras
      - text: "{{< iconify academicons google-scholar size=xl >}}"
        href: https://scholar.google.com/citations?user=zFUrGToAAAAJ&hl=en&oi=ao
      - icon: rss
        href: posts.xml
  page-footer:
    right:
      - text: blog source
        href: https://github.com/shamindras/ss_personal_quarto_blog

lang: en

format:
  html:
    theme: assets/css/ember.scss
    css: assets/css/styles.css
    html-math-method: mathjax
